<?xml version="1.0"?>
<!DOCTYPE hbci [
    <!ELEMENT hbci (DEGs , SEGs , MSGs)>
    <!ATTLIST hbci version CDATA #REQUIRED>
    
    <!ELEMENT DEGs (DEGdef)*>
    <!ELEMENT SEGs (SEGdef)*>
    <!ELEMENT MSGs (MSGdef)*>
    <!ELEMENT SFs (SFdef)*>
    
    <!ELEMENT DEGdef ((DE | DEG)+ , valids* , value*)>
    <!ATTLIST DEGdef id ID #REQUIRED>
    <!ATTLIST DEGdef needsRequestTag (1) #IMPLIED>
    
    <!ELEMENT SEGdef (SEGVersion+ , valids* , value*)>
    <!ATTLIST SEGdef id ID #REQUIRED>
    <!ATTLIST SEGdef code CDATA #REQUIRED>
    <!ATTLIST SEGdef needsRequestTag (1) #IMPLIED>

    <!ELEMENT SEGVersion ((DEG | DE)+ , valids* , value*)>
    <!ATTLIST SEGVersion id CDATA #REQUIRED>
    
    <!ELEMENT SFdef (SEG | SF)*>
    <!ATTLIST SFdef id ID #REQUIRED needsRequestTag (1) #IMPLIED>
    <!ATTLIST SFdef ordered (1) #IMPLIED>
        
    <!ELEMENT MSGdef ((SEG | SF)+ , valids* , default*)>
    <!ATTLIST MSGdef id ID #REQUIRED>
    <!ATTLIST MSGdef dontsign (1) #IMPLIED>
    <!ATTLIST MSGdef dontcrypt (1) #IMPLIED>
    
    <!ELEMENT DE EMPTY>
    <!ATTLIST DE name CDATA #REQUIRED>
    <!ATTLIST DE type (AN | Bin | Code | Ctr | Cur | DTAUS | Date | Dig | ID | JN | Num | Time | Wrt) #REQUIRED>
    <!ATTLIST DE minsize CDATA #IMPLIED>
    <!ATTLIST DE maxsize CDATA #IMPLIED>
    <!ATTLIST DE minnum CDATA #IMPLIED>
    <!ATTLIST DE maxnum CDATA #IMPLIED>
    
    <!ELEMENT DEG EMPTY>
    <!ATTLIST DEG type IDREF #REQUIRED>
    <!ATTLIST DEG name CDATA #IMPLIED>
    <!ATTLIST DEG minnum CDATA #IMPLIED>
    <!ATTLIST DEG maxnum CDATA #IMPLIED>
    
    <!ELEMENT SF EMPTY>
    <!ATTLIST SF type IDREF #REQUIRED>
    <!ATTLIST SF name CDATA #IMPLIED>
    <!ATTLIST SF minnum CDATA #IMPLIED>
    <!ATTLIST SF maxnum CDATA #IMPLIED>
        
    <!ELEMENT SEG EMPTY>
    <!ATTLIST SEG type IDREF #REQUIRED>
    <!ATTLIST SEG name CDATA #IMPLIED>
    <!ATTLIST SEG minnum CDATA #IMPLIED>
    <!ATTLIST SEG maxnum CDATA #IMPLIED>
    
    <!ELEMENT valids (validvalue)+>
    <!ATTLIST valids path CDATA #REQUIRED>
    
    <!ELEMENT validvalue (#PCDATA)>
    
    <!ELEMENT value (#PCDATA)>
    <!ATTLIST value path CDATA #REQUIRED>
    
    <!ELEMENT default (#PCDATA)>
    <!ATTLIST default path CDATA #REQUIRED>

<!ENTITY MsgSigHeadInst
'<SEG type="MsgHeadInst" name="MsgHead"/>
<SEG type="SigHeadInst" name="SigHead" minnum="0"/>'
>

<!ENTITY MsgSigTailInst
'<SEG type="SigTailInst" name="SigTail" minnum="0"/>
<SEG type="MsgTailInst" name="MsgTail"/>'
>


<!ENTITY GVP
'<!-- 2.01 -->
<DEG type="SegHead" name="SegHead"/>
<DE name="maxnum" type="Num" maxsize="3"/>
<DE name="minsigs" type="Num" maxsize="1"/>'
>
<!ENTITY GVP2
'<!-- 3.0 -->
<DEG type="SegHead" name="SegHead"/>
<DE name="maxnum" type="Num" maxsize="3"/>
<DE name="minsigs" type="Num" maxsize="1"/>
<DE name="secclass" type="Code" maxsize="1"/>'
>

<!ENTITY SecClassValids
'<valids path="secclass">
    <validvalue>0</validvalue>
    <validvalue>1</validvalue>
    <validvalue>2</validvalue>
    <validvalue>3</validvalue>
    <validvalue>4</validvalue>
</valids>'
>


]>

<hbci version="300">
    
    <DEGs>
        <DEGdef id="AllowedGV">
            <DE name="code" type="AN" maxsize="6"/>
            <DE name="reqSigs" type="Num" maxsize="2"/>
            <DE name="limittype" type="Code" maxsize="1" minnum="0"/>
            <!-- DEG type="BTG" minnum="0"/-->
            <DE name="value" type="Wrt" minnum="0"/>
            <DE name="curr" type="Cur" minnum="0"/>
            <DE name="limitdays" type="Num" maxsize="3" minnum="0"/>
            
            <valids path="reqSigs">
                <validvalue>0</validvalue>
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
                <validvalue>3</validvalue>
                
                <!-- Siehe http://www.onlinebanking-forum.de/phpBB2/viewtopic.php?t=14583 -->
                <validvalue>98</validvalue>
                <validvalue>99</validvalue>
            </valids>
            <valids path="limittype">
                <validvalue>E</validvalue>
                <validvalue>T</validvalue>
                <validvalue>W</validvalue>
                <validvalue>M</validvalue>
                <validvalue>Z</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="AnswerHHD_UC">
            <DE name="atc" type="AN" maxsize="6"/>
            <DE name="applicationCryptoAC" type="Bin" maxsize="256"/>
            <DE name="ef_id_data" type="Bin" maxsize="256"/>
            <DE name="cvr" type="Bin" maxsize="256"/>
            <DE name="versionInfo" type="Bin" maxsize="256"/>
        </DEGdef>
        
        <DEGdef id="KIK">
            <DE name="country" type="Ctr"/>
            <DE name="blz" type="AN" maxsize="30" minnum="0"/>
        </DEGdef>
        
        <DEGdef id="KTV2"> <!-- 2.2 -->
            <DE name="number" type="ID"/>
            <DE name="subnumber" type="ID" minnum="0"/>
            <DEG type="KIK"/>
        </DEGdef>
        
        <DEGdef id="KTVInt">
            <DE name="iban" type="AN" maxsize="34" minnum="0"/>
            <DE name="bic" type="AN" maxsize="11" minnum="0"/>
            <DE name="number" type="ID" minnum="0"/>
            <DE name="subnumber" type="ID" minnum="0"/>
            <DEG type="KIK" minnum="0"/>
        </DEGdef>

        <DEGdef id="SegHead">
            <DE name="code" type="AN" maxsize="6"/>
            <DE name="seq" type="Num" maxsize="3"/>
            <DE name="version" type="Num" maxsize="3"/>
            <DE name="ref" type="Num" maxsize="3" minnum="0"/>
        </DEGdef>
        
        <DEGdef id="MsgRef">
            <DE name="dialogid" type="ID"/>
            <DE name="msgnum" type="Num" maxsize="4"/>
        </DEGdef>
        
        <DEGdef id="SecProfile">
            <DE name="method" type="Code" minsize="3" maxsize="3"/>
            <DE name="version" type="Num" maxsize="3" maxnum="9"/>
            
            <valids path="method">
                <validvalue>DDV</validvalue>
                <validvalue>RDH</validvalue>
                <validvalue>PIN</validvalue>
            </valids>
            <valids path="version">
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
                <validvalue>3</validvalue>
                <validvalue>4</validvalue>
                <validvalue>5</validvalue>
                <validvalue>6</validvalue>
                <validvalue>7</validvalue>
                <validvalue>8</validvalue>
                <validvalue>9</validvalue>
                <validvalue>10</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="SecIdnDetails">
            <DE name="func" type="Code" maxsize="3"/>
            <DE name="cid" type="Bin" maxsize="256" minnum="0"/>
            <DE name="sysid" type="ID" minnum="0"/>
            
            <valids path="func">
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="SecTimestamp">
            <DE name="type" type="AN" maxsize="3"/>
            <DE name="date" type="Date" minnum="0"/>
            <DE name="time" type="Time" minnum="0"/>
            
            <valids path="type">
                <validvalue>1</validvalue>
                <validvalue>6</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="HashAlg">
            <DE name="usage" type="Code" maxsize="3"/>
            <DE name="alg" type="Code" maxsize="3"/>
            <DE name="parname" type="Code" maxsize="3"/>
            <DE name="parameter" type="Bin" maxsize="512" minnum="0"/>
            
            <valids path="alg">
                <validvalue>1</validvalue>
                <validvalue>3</validvalue>
                <validvalue>4</validvalue>
                <validvalue>5</validvalue>
                <validvalue>6</validvalue>
                <validvalue>999</validvalue>
            </valids>
            
            <value path="usage">1</value>
            <value path="parname">1</value>
        </DEGdef>
        
        <DEGdef id="SigAlg">
            <DE name="usage" type="Code" maxsize="3"/>
            <DE name="alg" type="Code" maxsize="3"/>
            <DE name="mode" type="AN" maxsize="999"/>
            
            <valids path="alg">
                <validvalue>1</validvalue>
                <validvalue>10</validvalue>
            </valids>
            <valids path="mode">
                <validvalue>999</validvalue>
                <validvalue>16</validvalue>
                <validvalue>17</validvalue>
                <validvalue>18</validvalue>
                <validvalue>19</validvalue>
            </valids>
            
            <value path="usage">6</value>
        </DEGdef>
        
        <DEGdef id="KeyName">
            <DE name="country" type="Ctr"/>
            <DE name="blz" type="AN" maxsize="30" minnum="0"/>
            <DE name="userid" type="ID"/>
            <DE name="keytype" type="AN" maxsize="1"/>
            <DE name="keynum" type="Num" maxsize="3"/>
            <DE name="keyversion" type="Num" maxsize="3"/>
            
            <valids path="keytype">
                <validvalue>D</validvalue>
                <validvalue>S</validvalue>
                <validvalue>V</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="Cert">
            <DE name="type" type="Code" maxsize="1"/>
            <DE name="cert" type="Bin" maxsize="2048"/>
            
            <valids path="type">
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
                <validvalue>3</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="UserSig">
            <DE name="pin" type="AN" maxsize="99"/>               <!-- Einige Banken unterstÃ¼tzen mehr als 6 Stellen  -->
            <DE name="tan" type="AN" maxsize="99" minnum="0"/>
        </DEGdef>
        
        <DEGdef id="RetVal">
            <DE name="code" type="Dig" minsize="4" maxsize="4"/>
            <DE name="ref" type="AN" maxsize="7" minnum="0"/>
            <DE name="text" type="AN" maxsize="80"/>
            <DE name="parm" type="AN" maxsize="35" minnum="0" maxnum="10"/>
        </DEGdef>
        
        <DEGdef id="CommParam">
            <DE name="dienst" type="AN" maxsize="2"/>
            <DE name="addr" type="AN" maxsize="512"/>
            <DE name="addr2" type="AN" maxsize="512" minnum="0"/>
            <DE name="filter" type="AN" minsize="3" maxsize="3" minnum="0"/>
            <DE name="filterversion" type="Num" maxsize="3" minnum="0"/>
            
            <valids path="dienst">
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
                <validvalue>3</validvalue>
            </valids>
            <valids path="filter">
                <validvalue>MIM</validvalue>
                <validvalue>UUE</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="SuppCamtFormats">
            <DE name="camt_descriptor" type="AN" minsize="1" maxsize="256" minnum="1" maxnum="99"/>
        </DEGdef>      
        
        <DEGdef id="SuppSecMethods">
            <DE name="method" type="AN" minsize="3" maxsize="3"/>
            <DE name="version" type="Num" maxsize="3" maxnum="9"/>
        </DEGdef>
        
        <DEGdef id="SuppCompMethods">
            <DE name="func" type="Code" maxsize="3"/>
            <DE name="version" type="Num" maxsize="3" maxnum="9"/>
            
            <valids path="func">
                <validvalue>0</validvalue>
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
                <validvalue>3</validvalue>
                <validvalue>4</validvalue>
                <validvalue>5</validvalue>
                <validvalue>6</validvalue>
                <validvalue>7</validvalue>
                <validvalue>999</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="SuppLangs">
            <DE name="lang" type="Num" maxsize="3" maxnum="9"/>
            
            <valids path="lang">
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
                <validvalue>3</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="SuppVersions">
            <DE name="version" type="Num" maxsize="3" maxnum="9"/>
            
            <valids path="version">
                <validvalue>201</validvalue>
                <validvalue>210</validvalue>
                <validvalue>220</validvalue>
                <validvalue>300</validvalue>
                <validvalue>400</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="BookedCamtStatements">
            <DE name="statement" type="Bin" minnum="0" maxnum="999"/>
        </DEGdef>
        
        <DEGdef id="KLimit">
            <DE name="limittype" type="Code" maxsize="1"/>
            <!-- DEG type="BTG" minnum="0"/-->
            <DE name="value" type="Wrt" minnum="0"/>
            <DE name="curr" type="Cur" minnum="0"/>
            <DE name="limitdays" type="Num" maxsize="3" minnum="0"/>

            <valids path="limittype">
                <validvalue>E</validvalue>
                <validvalue>T</validvalue>
                <validvalue>W</validvalue>
                <validvalue>M</validvalue>
                <validvalue>Z</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="TANProcessParams1">
            <DE name="secfunc" type="Code" maxsize="3"/>
            <DE name="process" type="Code" maxsize="1"/>
            <DE name="id" type="ID"/>
            <DE name="name" type="AN" maxsize="30"/>
            <DE name="maxlentan" type="Num" maxsize="2"/>
            <DE name="tanformat" type="Code" maxsize="1"/>
            <DE name="inputinfo" type="AN" maxsize="30"/>
            <DE name="maxleninput" type="Num" maxsize="3"/>
            <DE name="noftanlists" type="Num" maxsize="1" minnum="0"/>
            <DE name="canmultitan" type="JN"/>
            <DE name="cantandelay" type="JN"/>
            
            <valids path="process">
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
            <valids path="tanformat">
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="TANProcessParams2">
            <DE name="secfunc" type="Code" maxsize="3"/>
            <DE name="process" type="Code" maxsize="1"/>
            <DE name="id" type="ID"/>
            <DE name="name" type="AN" maxsize="30"/>
            <DE name="maxlentan" type="Num" maxsize="2"/>
            <DE name="tanformat" type="Code" maxsize="1"/>
            <DE name="inputinfo" type="AN" maxsize="30"/>
            <DE name="maxleninput" type="Num" maxsize="3"/>
            <DE name="noftanlists" type="Num" maxsize="1" minnum="0"/>
            <DE name="canmultitan" type="JN"/>
            <DE name="cantandelay" type="Code" maxsize="1"/>
            <DE name="needtanlistidx" type="Code" maxsize="1"/>
            <DE name="canstorno" type="JN"/>
            <DE name="needchallengeclass" type="JN"/>
            <DE name="needchallengevalue" type="JN"/>
            
            <valids path="process">
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
            <valids path="tanformat">
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="TANProcessParams3">
            <DE name="secfunc" type="Code" maxsize="3"/>
            <DE name="process" type="Code" maxsize="1"/>
            <DE name="id" type="ID"/>
            <DE name="name" type="AN" maxsize="30"/>
            <DE name="maxlentan" type="Num" maxsize="2"/>
            <DE name="tanformat" type="Code" maxsize="1"/>
            <DE name="inputinfo" type="AN" maxsize="30"/>
            <DE name="maxleninput" type="Num" maxsize="3"/>
            <DE name="noftanlists" type="Num" maxsize="1" minnum="0"/>
            <DE name="canmultitan" type="JN"/>
            <DE name="cantandelay" type="Code" maxsize="1"/>
            <DE name="needtanlistidx" type="Code" maxsize="1"/>
            <DE name="canstorno" type="JN"/>
            <DE name="needchallengeclass" type="JN"/>
            <DE name="needchallengevalue" type="JN"/>
            <DE name="initmode" type="Code"/>
            <DE name="needtanmedia" type="Code"/>
            <DE name="nofactivetanmedia" type="Num" maxsize="1" minnum="0"/>
            
            <valids path="process">
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
            <valids path="tanformat">
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="TANProcessParams4">
            <DE name="secfunc" type="Code" maxsize="3"/>
            <DE name="process" type="Code" maxsize="1"/>
            <DE name="id" type="ID"/>
	       <DE name="zkamethod_name" type="AN" maxsize="32" minnum="0" />
	       <DE name="zkamethod_version" type="AN" maxsize="10" minnum="0" />
            <DE name="name" type="AN" maxsize="30"/>
            <DE name="maxlentan" type="Num" maxsize="2"/>
            <DE name="tanformat" type="Code" maxsize="1"/>
            <DE name="inputinfo" type="AN" maxsize="30"/>
            <DE name="maxleninput" type="Num" maxsize="3"/>
            <DE name="noftanlists" type="Num" maxsize="1" minnum="0"/>
            <DE name="canmultitan" type="JN"/>
            <DE name="cantandelay" type="Code" maxsize="1"/>
            <DE name="needtanlistidx" type="Code" maxsize="1"/>
            <DE name="canstorno" type="JN"/>
	        <DE name="needsmsaccount" type="JN" />
            <DE name="needchallengeclass" type="JN"/>
            <DE name="needchallengevalue" type="JN"/>
	       <DE name="ischallengestructured" type="JN" />
            <DE name="initmode" type="Code"/>
            <DE name="needtanmedia" type="Code"/>
            <DE name="nofactivetanmedia" type="Num" maxsize="1" minnum="0"/>
            
            <valids path="process">
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
            <valids path="tanformat">
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
        </DEGdef>
        
        
        <DEGdef id="TANProcessParams5">
            <DE name="secfunc" type="Code" maxsize="3"/>
            <DE name="process" type="Code" maxsize="1"/>
            <DE name="id" type="ID"/>
            <DE name="zkamethod_name" type="AN" maxsize="32" minnum="0" />
            <DE name="zkamethod_version" type="AN" maxsize="10" minnum="0" />
            <DE name="name" type="AN" maxsize="30"/>
            <DE name="maxlentan" type="Num" maxsize="2"/>
            <DE name="tanformat" type="Code" maxsize="1"/>
            <DE name="inputinfo" type="AN" maxsize="30"/>
            <DE name="maxleninput" type="Num" maxsize="4"/>
            <DE name="noftanlists" type="Num" maxsize="1" minnum="0"/>
            <DE name="canmultitan" type="JN"/>
            <DE name="cantandelay" type="Code" maxsize="1"/>
            <DE name="needtanlistidx" type="Code" maxsize="1"/>
            <DE name="canstorno" type="JN"/>
            <DE name="needsmsaccount" type="Code" maxsize="1"/>
            <DE name="needorderaccount" type="Code" maxsize="1"/>
            <DE name="needchallengeclass" type="JN"/>
            <DE name="ischallengestructured" type="JN" />
            <DE name="initmode" type="Code"/>
            <DE name="needtanmedia" type="Code"/>
            <DE name="nofactivetanmedia" type="Num" maxsize="1" minnum="0"/>
            
            <valids path="process">
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
            <valids path="tanformat">
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="TANProcessParams6">
            <DE name="secfunc" type="Code" maxsize="3"/>
            <DE name="process" type="Code" maxsize="1"/>
            <DE name="id" type="ID"/>
            <DE name="zkamethod_name" type="AN" maxsize="32" minnum="0" />
            <DE name="zkamethod_version" type="AN" maxsize="10" minnum="0" />
            <DE name="name" type="AN" maxsize="30"/>
            <DE name="maxlentan" type="Num" maxsize="2"/>
            <DE name="tanformat" type="Code" maxsize="1"/>
            <DE name="inputinfo" type="AN" maxsize="30"/>
            <DE name="maxleninput" type="Num" maxsize="4"/>
            <DE name="canmultitan" type="JN"/>
            <DE name="cantandelay" type="Code" maxsize="1"/>
            <DE name="canstorno" type="JN"/>
            <DE name="needsmsaccount" type="Code" maxsize="1"/>
            <DE name="needorderaccount" type="Code" maxsize="1"/>
            <DE name="needchallengeclass" type="JN"/>
            <DE name="ischallengestructured" type="JN" />
            <DE name="initmode" type="Code"/>
            <DE name="needtanmedia" type="Code"/>
            <DE name="needHHDUCanswer" type="JN"/>
            <DE name="nofactivetanmedia" type="Num" maxsize="1" minnum="0"/>
            
            <valids path="process">
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
            <valids path="tanformat">
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="TANProcessParams7">
            <DE name="secfunc" type="Code" maxsize="3"/>
            <DE name="process" type="Code" maxsize="1"/>
            <DE name="id" type="ID"/>
            <DE name="zkamethod_name" type="AN" maxsize="32" minnum="0" />
            <DE name="zkamethod_version" type="AN" maxsize="10" minnum="0" />
            <DE name="name" type="AN" maxsize="30"/>
            <DE name="maxlentan" type="Num" maxsize="2" minnum="0"/>
            <DE name="tanformat" type="Code" maxsize="1" minnum="0"/>
            <DE name="inputinfo" type="AN" maxsize="30"/>
            <DE name="maxleninput" type="Num" maxsize="4"/>
            <DE name="canmultitan" type="JN"/>
            <DE name="cantandelay" type="Code" maxsize="1"/>
            <DE name="canstorno" type="JN"/>
            <DE name="needsmsaccount" type="Code" maxsize="1"/>
            <DE name="needorderaccount" type="Code" maxsize="1"/>
            <DE name="needchallengeclass" type="JN"/>
            <DE name="ischallengestructured" type="JN" />
            <DE name="initmode" type="Code"/>
            <DE name="needtanmedia" type="Code"/>
            <DE name="needHHDUCanswer" type="JN"/>
            <DE name="nofactivetanmedia" type="Num" maxsize="1" minnum="0"/>
            <DE name="maxpolls_decoupled" type="Num" maxsize="3" minnum="0"/>
            <DE name="firstwait_decoupled" type="Num" maxsize="3" minnum="0"/>
            <DE name="nextwait_decoupled" type="Num" maxsize="3" minnum="0"/>
            <DE name="canconfirm_decoupled" type="JN" minnum="0"/>
            <DE name="canpoll_decoupled" type="JN" minnum="0"/>
            
            <valids path="process">
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
            <valids path="tanformat">
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
        </DEGdef>       
        
         <DEGdef id="ParTAN1">
            <DE name="can1step" type="JN"/>
            <DE name="canmultitangvs" type="JN"/>
            <DE name="orderhashmode" type="Code" maxsize="1"/>
            <DE name="instsig" type="Code" maxsize="1"/>
            <DEG type="TANProcessParams1" name="TANProcessParams" maxnum="98"/>
            
            <valids path="orderhashmode">
                <validvalue>0</validvalue>
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
            <valids path="instsig">
                <validvalue>0</validvalue>
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
        </DEGdef>
        
         <DEGdef id="ParTAN2">
            <DE name="can1step" type="JN"/>
            <DE name="canmultitangvs" type="JN"/>
            <DE name="orderhashmode" type="Code" maxsize="1"/>
            <DEG type="TANProcessParams2" name="TANProcessParams" maxnum="98"/>
            
            <valids path="orderhashmode">
                <validvalue>0</validvalue>
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="ParTAN3">
            <DE name="can1step" type="JN"/>
            <DE name="canmultitangvs" type="JN"/>
            <DE name="orderhashmode" type="Code" maxsize="1"/>
            <DEG type="TANProcessParams3" name="TANProcessParams" maxnum="98"/>
            
            <valids path="orderhashmode">
                <validvalue>0</validvalue>
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
        </DEGdef>

        <DEGdef id="ParTAN4">
            <DE name="can1step" type="JN"/>
            <DE name="canmultitangvs" type="JN"/>
            <DE name="orderhashmode" type="Code" maxsize="1"/>
            <DEG type="TANProcessParams4" name="TANProcessParams" maxnum="98"/>
            
            <valids path="orderhashmode">
                <validvalue>0</validvalue>
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
        </DEGdef>

        <DEGdef id="ParTAN5">
            <DE name="can1step" type="JN"/>
            <DE name="canmultitangvs" type="JN"/>
            <DE name="orderhashmode" type="Code" maxsize="1"/>
            <DEG type="TANProcessParams5" name="TANProcessParams" maxnum="98"/>
            
            <valids path="orderhashmode">
                <validvalue>0</validvalue>
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
        </DEGdef>

        <DEGdef id="ParTAN6">
            <DE name="can1step" type="JN"/>
            <DE name="canmultitangvs" type="JN"/>
            <DE name="orderhashmode" type="Code" maxsize="1"/>
            <DEG type="TANProcessParams6" name="TANProcessParams" maxnum="98"/>
            
            <valids path="orderhashmode">
                <validvalue>0</validvalue>
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="ParTAN7">
            <DE name="can1step" type="JN"/>
            <DE name="canmultitangvs" type="JN"/>
            <DE name="orderhashmode" type="Code" maxsize="1"/>
            <DEG type="TANProcessParams7" name="TANProcessParams" maxnum="98"/>
            
            <valids path="orderhashmode">
                <validvalue>0</validvalue>
                <validvalue>1</validvalue>
                <validvalue>2</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="CryptAlg">
            <DE name="use" type="Code" maxsize="3"/>
            <DE name="mode" type="Code" maxsize="3"/>
            <DE name="alg" type="Code" maxsize="3"/>
            <DE name="enckey" type="Bin" maxsize="512"/>
            <DE name="keytype" type="Code" maxsize="3"/>
            <DE name="ivname" type="Code" maxsize="3"/>
            <DE name="iv" type="Bin" maxsize="512" minnum="0"/>

            <valids path="mode">
                <validvalue>2</validvalue>
                <validvalue>16</validvalue>
                <validvalue>17</validvalue>
                <validvalue>18</validvalue>
                <validvalue>19</validvalue>
            </valids>
            <valids path="alg">
                <validvalue>13</validvalue>
            </valids>
            <valids path="keytype">
                <validvalue>5</validvalue>
                <validvalue>6</validvalue>
            </valids>

            <value path="use">2</value>
            <value path="ivname">1</value>
        </DEGdef>
        
        <DEGdef id="BTG">
            <DE name="value" type="Wrt"/>
            <DE name="curr" type="Cur"/>
        </DEGdef>

        
        <DEGdef id="Balance">  <!-- 3.0 -->
            <DE name="debitcredit" type="Code" maxsize="1"/>
            <DE name="value" type="Wrt"/>
            <DE name="curr" type="Cur"/>
            <DE name="date" type="Date"/>
            <DE name="time" type="Time" minnum="0"/>

            <valids path="debitcredit">
                <validvalue>C</validvalue>
                <validvalue>D</validvalue>
            </valids>
        </DEGdef>
        
        <DEGdef id="Timestamp">
            <DE name="date" type="Date"/>
            <DE name="time" type="Time" minnum="0"/>
        </DEGdef>

        <DEGdef id="ParStatements"> <!-- 2.2 -->
            <DE name="timerange" type="Num" maxsize="4"/>
            <DE name="canmaxentries" type="JN"/>
            <DE name="canallaccounts" type="JN"/>
        </DEGdef>
        
        <DEGdef id="CamtParStatements">
            <DE name="timerange" type="Num" maxsize="4"/>
            <DE name="canmaxentries" type="JN"/>
            <DE name="canallaccounts" type="JN"/>
            <DE name="suppformats" type="AN" minnum="1" maxnum="99"/>